### ISSUE TITLE
implement SchemaEditor.add/alter/remove_field()

### ISSUE THREAD

**Issue by timgraham** [mongodb-labs/django-mongodb#115]
Should these operations try to follow what Django does on SQL backends as much as possible?

For example, if adding a field with a default, Django will populate the default value on existing rows. Should MongoDB do it? If so, what about if there's no value to be populated? Should the field not be added to existing documents? We might be able to do that for nullable fields, but perhaps not for string-based fields where `null=False` and the default is an empty string.

**Comment by Jibola** [comment]
I'm willing to take a group vote here, but here's my take:

Questions: 
> if adding a field with a default, Django will populate the default value on existing rows. Should MongoDB do it?
**Yes**

> If so, what about if there's no value to be populated? Should the field not be added to existing documents?
**The field SHOULD be added to reduce bug issues; this is a point I am willing to discuss**

My larger sentiment is let's keep to how Django handles SQL backends generally to reduce any potential errors that could arise from assumptions made elsewhere in the code. 


Considerations : 
* What happens when the data needs to be retrieved? If the value is empty, do we null out the field entirely?
    * If no field exists, then we may need a special object representation because None/null is a valid value that signifies a field's existence. Something like `Undefined` in JavaScript would need to be there.
* What's the existing paradigm in MongoDB?
     * If you don't need it, don't put it there, really. 
* What's the existing paradigm in SQL?
     * All rows and columns are explicitly defined so there is never an "undefined" row/column
