### ISSUE TITLE
PYTHON-4802: add support for sqlmigrate

### ISSUE THREAD

**Issue by timgraham** [mongodb-labs/django-mongodb#141]
Currently `SchemaEditor` doesn't log queries and thus the `sqlmigrate` command doesn't work.

Reference: [Django's implementation](https://github.com/django/django/blob/main/django/db/backends/base/schema.py#L148)

Also see: [CollectionDebugWrapper](https://github.com/mongodb-labs/django-mongodb/blob/41598ec6549aaf6ca21ea349fb0c323d319b618b/django_mongodb/utils.py#L28)

**Comment by aclark4life** [comment]
> Currently `SchemaEditor` doesn't log queries 

Django core's `SchemaEditor` doesn't log queries because … logging queries is not a feature of the Django core, correct? In other words, via the `BaseSchemaEditor` doc string its job is "emitting schema-changing statements to the databases" not logging them.

> and thus the `sqlmigrate` command doesn't work.

Can you clarify the connection between the `SchemaEditor` and `sqlmigrate` command? IIUC, "thus it doesn't work" includes the assumption we want to use some MongoDB-specific `SchemaEditor` implementation to log queries in order to output `as_mql` ?

**Comment by timgraham** [comment]
By "log queries" I mean appending to [`SchemaEditor.collected_sql`](https://github.com/django/django/blob/73e8e811416dcb5007ad9cc9d1632aaca95bf302/django/db/backends/base/schema.py#L192-L199). `sqlmigrate` gets its output from `collected_sql`.
